server:
  error:
    include-message: always

spring:
  profiles:
    active: prod
  thymeleaf:
    cache: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

airport:
  discount:
    def:
      percent: 20
    special:
      percent: 15
      limit: 10000

