spring:
  profiles:
    active: smart

employee:
  salary-raise:
    #for SmartEmployeeService
    categories:
      - year-limit: 10
        percent: 50
      - year-limit: 50
        percent: 50
      - year-limit: 2.5
        percent: 2
    base:
      percent: 0
    #for DefaultEmployeeService
    default-raise:
      percent: 5
